name: Lfelizphotography
favicon: null
layout_spectrum: 0.59867
typography_spectrum: 0.6395985917188227
title: PHOTOGRAPHY PAGE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#393939'
    - '#585858'
    - '#a7a7a7'
    - '#fdfdfd'
  brandStrength: 0
  lightness: 0.4914603321813047
  saturation: 0.4695118176750839
  rhythmicContrast: 0.2681480401661247
purpose: []
